name: haka_comic
description: "A third-party PICACG project."
publish_to: "none"

version: 1.1.1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: 3.38.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  dio: ^5.9.0
  crypto: ^3.0.6
  json_annotation: ^4.9.0
  # cached_network_image: ^3.4.1
  scrollable_positioned_list: ^0.3.8
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  sqlite_async: ^0.12.1
  provider: ^6.1.5+1
  dynamic_color: ^1.8.1
  path: ^1.9.1
  url_launcher: ^6.3.2
  yaml: ^3.1.3
  jiffy: ^6.4.4
  version: ^3.0.2
  photo_view:
    git:
      url: https://github.com/raoxwup/photo_view.git
      ref: d951ef08d4461a778ac3c95da2e4d1fe7a2e6881
  # photo_view:
  #   path: D:/Projects/practice/Flutter/photo_view
  file_picker: ^10.3.8
  webdav_client: ^1.2.2
  window_manager: ^0.5.1
  vector_math: ^2.2.0
  volume_button_override: ^0.0.1
  go_transitions: ^0.8.3
  # windows平台构建时tree shake对第三方图标不生效 导致构建产物体积过大
  # https://github.com/flutter/flutter/issues/157216
  material_symbols_icons: ^4.2892.0
  rust_lib_haka_comic:
    path: rust_builder
  flutter_rust_bridge: ^2.11.1
  legalize: ^1.2.2
  local_auth: ^3.0.0
  pool: ^1.5.2
  share_plus: ^12.0.1
  flutter_context_menu: ^0.4.1
  permission_handler: ^12.0.1
  save_to_folder_ios: ^1.0.4
  freezed_annotation: ^3.1.0
  extended_image: ^10.0.1
  flutter_displaymode: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.3
  package_rename: ^1.10.0
  freezed: ^3.2.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/splash/splash-icon-dark.png
    - assets/icons/splash/splash-icon-light.png
    - assets/images/login.png
    - assets/images/icon_empty.png
    - assets/images/icon_no_comment.png
    - assets/images/user.png
    - assets/images/leaderboard.jpg
    - assets/images/forum.jpg
    - assets/images/latest.jpg
    - assets/images/random.jpg
    - assets/images/default_avatar.jpg
    - assets/icons/ios/Light.png
    - assets/icons/ios/Dark.png
  # fonts:
