name: haka_comic
description: "A third-party PICACG project."
publish_to: "none"

version: 1.0.2

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.35.6

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  crypto: ^3.0.6
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  scrollable_positioned_list: ^0.3.8
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  sqlite_async: ^0.12.1
  provider: ^6.1.4
  dynamic_color: ^1.8.1
  flutter_cache_manager: ^3.4.1
  path: ^1.9.1
  url_launcher: ^6.3.1
  yaml: ^3.1.3
  photo_view:
    git:
      url: https://github.com/raoxwup/photo_view.git
      ref: ba2e5d829dfd1091eaa84678034ae27615d17bd9
  # photo_view:
  #   path: D:/Projects/practice/Flutter/photo_view
  file_picker: ^10.3.3
  webdav_client: ^1.2.2
  window_manager: ^0.5.1
  vector_math: ^2.2.0
  volume_button_override: ^0.0.1
  go_transitions: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.3
  package_rename: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/splash/splash-icon-dark.png
    - assets/icons/splash/splash-icon-light.png
    - assets/images/login.png
    - assets/images/icon_empty.png
    - assets/images/icon_no_comment.png
    - assets/images/user.png
    - assets/images/leaderboard.jpg
    - assets/images/forum.jpg
    - assets/images/latest.jpg
    - assets/images/random.jpg
    - assets/icons/ios/Light.png
    - assets/icons/ios/Dark.png
